#!/bin/bash

mkdir outputs/sounds && 
cp outputs/voice_menu.txt outputs/sounds/voice_menu && 
cd outputs/sounds && 
chmod +x voice_menu && 
./voice_menu

sox -n -c 1 -b 16 silence.wav trim 0.0 0.12 rate 22050
for f in *.aiff; do sox -c 1 silence.wav "$f" --encoding signed-integer --endian little "${f%.*}.raw" highpass 800 gain 20 norm -1 rate 8k tempo 1.1; done

mkdir aiff && 
mv *.aiff aiff/ && 
mkdir raw && 
mv *.raw raw/